### ISSUE TITLE
Symbols are HTML encoded in Moving from SQL Server to Couchbase Part 2

### ISSUE THREAD

**Issue by PaulTFreedman** [couchbaselabs/blog-source-code#1]
https://blog.couchbase.com/sql-server-couchbase-data-migration/

In the code samples that appear on the blog some symbols appear encoded

e.g. "<" shows as "\&lt;"

**Comment by PaulTFreedman** [comment]
![image](https://user-images.githubusercontent.com/20032260/52672381-9c9f1200-2f15-11e9-9d65-f621de5a6945.png)

**Comment by mgroves** [comment]
Yep, that's because we changed our syntax highlighting plugin after I wrote that post. I'd have to go back and make a (minor) fix to all those posts. While I'm fixing this one, are there any other posts where this is a problem for you?

**Comment by PaulTFreedman** [comment]
Just looking through the series again and I've noticed it's there for parts 1 and 3 as well:
https://blog.couchbase.com/moving-from-sql-server-to-couchbase-part-1-data-modeling/
https://blog.couchbase.com/moving-sql-server-couchbase-app-migration/

Not a big problem at all but I thought I'd flag it.

**Comment by mgroves** [comment]
I got those three posts corrected. Thanks very much for your help, and thanks for reading! If you'd ever like to talk about .NET / SQL / Couchbase some more, my door is always open to the community. You can join community.couchbase.com, email me, or just open an issue here.
